name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build web
        working-directory: web
        run: |
          npm ci || npm i
          npm run build
      - name: Setup Firebase
        run: npm i -g firebase-tools
      - name: Firebase deploy
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/sa.json
          firebase auth:login:ci --no-localhost || true
          firebase use $FIREBASE_PROJECT_ID
          firebase deploy --project $FIREBASE_PROJECT_ID --token "$(cat ${HOME}/sa.json | jq -r '.private_key_id')" || firebase deploy --project $FIREBASE_PROJECT_ID
